version: "3.8"

services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - trustscore-net

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - trustscore-net

volumes:
  pgdata:

networks:
  trustscore-net:
